import type { BathroomNearby } from "../../types/database";

// Mock data for the Map tab while it's not wired to Supabase yet (see
// src/features/bathrooms/api.ts for the real get_verified_bathrooms_nearby
// call this will be swapped for). Shaped exactly like BathroomNearby so the
// screen/components don't need to change when the real data lands - only
// the data source does.
//
// Coordinates are real Washington DC neighborhoods, mirroring
// supabase/seed/seed.sql's flavor (not the same rows - this is independent
// throwaway UI mock data, not seeded into any database).
export const MOCK_BATHROOMS: BathroomNearby[] = [
  {
    id: "mock-1",
    name: "Eastern Market Plaza Restroom",
    venue_name: "Eastern Market Plaza",
    description: "City-maintained public restroom right outside the market hall.",
    address: "225 7th St SE",
    city: "Washington",
    region: "DC",
    country: "USA",
    floor: "Ground floor",
    latitude: 38.8847,
    longitude: -76.9956,
    status: "verified",
    access_type: "public",
    purchase_required: false,
    purchase_note: null,
    access_difficulty: "easy",
    access_notes: null,
    access_code_public_allowed: false,
    cost_type: "free",
    cost_amount: null,
    gender_category: "all_gender",
    toilet_type: "sitting",
    amenities: { toilet_paper: true, soap: true, hand_dryer: true, wheelchair_accessible: true },
    tags: ["clean", "emergency_save"],
    open_hours: { is_24_hours: false, open: "07:00", close: "20:00" },
    cleanliness_score: 4.3,
    safety_score: 4.1,
    privacy_score: 3.8,
    smell_score: 4.0,
    prestige_score: 2.1,
    overall_score: 4.2,
    review_count: 12,
    photo_count: 3,
    verified_at: "2026-04-01T00:00:00.000Z",
    last_verified_at: "2026-06-15T00:00:00.000Z",
    distance_meters: 320,
  },
  {
    id: "mock-2",
    name: "Capitol Grounds Coffee",
    venue_name: "Capitol Grounds Coffee",
    description: "Single-occupancy restroom behind the espresso bar.",
    address: "301 Pennsylvania Ave SE",
    city: "Washington",
    region: "DC",
    country: "USA",
    floor: "1",
    latitude: 38.8857,
    longitude: -76.9942,
    status: "verified",
    access_type: "purchase_required",
    purchase_required: true,
    purchase_note: "Must buy any menu item",
    access_difficulty: "easy",
    access_notes: "Ask the barista for the key after you order",
    access_code_public_allowed: false,
    cost_type: "purchase_required",
    cost_amount: null,
    gender_category: "all_gender",
    toilet_type: "sitting",
    amenities: { toilet_paper: true, soap: true, hand_dryer: true, mirror: true },
    tags: ["clean", "restaurant"],
    open_hours: { is_24_hours: false, open: "06:30", close: "19:00" },
    cleanliness_score: 4.0,
    safety_score: 4.4,
    privacy_score: 3.9,
    smell_score: 3.8,
    prestige_score: 2.6,
    overall_score: 4.0,
    review_count: 8,
    photo_count: 1,
    verified_at: "2026-04-10T00:00:00.000Z",
    last_verified_at: "2026-06-01T00:00:00.000Z",
    distance_meters: 540,
  },
  {
    id: "mock-3",
    name: "The Meridian Hotel Lobby",
    venue_name: "The Meridian Hotel",
    description: "Marble-and-brass restroom tucked past the lobby bar.",
    address: "1500 New Hampshire Ave NW",
    city: "Washington",
    region: "DC",
    country: "USA",
    floor: "Lobby",
    latitude: 38.9097,
    longitude: -77.0434,
    status: "verified",
    access_type: "ask_staff",
    purchase_required: false,
    purchase_note: null,
    access_difficulty: "easy",
    access_notes: "Walk in like you belong, restrooms are past the lobby bar",
    access_code_public_allowed: false,
    cost_type: "free",
    cost_amount: null,
    gender_category: "all_gender",
    toilet_type: "sitting",
    amenities: { mirror: true, full_length_mirror: true, soap: true, hand_dryer: true, outlet: true },
    tags: ["hotel", "luxury", "elite", "outfit_check"],
    open_hours: { is_24_hours: true },
    cleanliness_score: 4.8,
    safety_score: 4.7,
    privacy_score: 4.5,
    smell_score: 4.6,
    prestige_score: 4.9,
    overall_score: 4.8,
    review_count: 21,
    photo_count: 5,
    verified_at: "2026-03-20T00:00:00.000Z",
    last_verified_at: "2026-06-20T00:00:00.000Z",
    distance_meters: 1850,
  },
  {
    id: "mock-4",
    name: "Foggy Bottom University Student Center",
    venue_name: "University Student Center",
    description: "3rd floor restroom, usually empty between classes.",
    address: "800 21st St NW",
    city: "Washington",
    region: "DC",
    country: "USA",
    floor: "3",
    latitude: 38.9,
    longitude: -77.0481,
    status: "verified",
    access_type: "public",
    purchase_required: false,
    purchase_note: null,
    access_difficulty: "easy",
    access_notes: null,
    access_code_public_allowed: false,
    cost_type: "free",
    cost_amount: null,
    gender_category: "all_gender",
    toilet_type: "mixed",
    amenities: { toilet_paper: true, soap: true, hand_dryer: true, wheelchair_accessible: true },
    tags: ["campus", "emergency_save", "no_line"],
    open_hours: { is_24_hours: false, open: "07:00", close: "23:00" },
    cleanliness_score: 3.4,
    safety_score: 3.9,
    privacy_score: 3.5,
    smell_score: 3.3,
    prestige_score: 1.8,
    overall_score: 3.5,
    review_count: 16,
    photo_count: 0,
    verified_at: "2026-02-28T00:00:00.000Z",
    last_verified_at: "2026-05-30T00:00:00.000Z",
    distance_meters: 2210,
  },
  {
    id: "mock-5",
    name: "The Hayworth Society Club",
    venue_name: "The Hayworth Society Club",
    description: "Members-only social club. The restroom alone is worth it.",
    address: "1523 Wisconsin Ave NW",
    city: "Washington",
    region: "DC",
    country: "USA",
    floor: "2",
    latitude: 38.9076,
    longitude: -77.0723,
    status: "verified",
    access_type: "private_rare",
    purchase_required: false,
    purchase_note: null,
    access_difficulty: "invite_only",
    access_notes: "Members-only; a member has to sign you in",
    access_code_public_allowed: false,
    cost_type: "free",
    cost_amount: null,
    gender_category: "all_gender",
    toilet_type: "bidet",
    amenities: { bidet: true, full_length_mirror: true, mirror: true, soap: true, outlet: true, touchless_flush: true },
    tags: ["luxury", "private_rare", "elite", "hidden_gem", "bidet"],
    open_hours: { is_24_hours: false, open: "11:00", close: "01:00" },
    cleanliness_score: 4.9,
    safety_score: 4.8,
    privacy_score: 4.9,
    smell_score: 4.7,
    prestige_score: 5.0,
    overall_score: 4.9,
    review_count: 6,
    photo_count: 2,
    verified_at: "2026-05-01T00:00:00.000Z",
    last_verified_at: "2026-06-18T00:00:00.000Z",
    distance_meters: 4120,
  },
  {
    id: "mock-6",
    name: "Tunnel Station Mart Restroom",
    venue_name: "Tunnel Station Mart",
    description: "Behind the snack aisle. Bring your own paper towels.",
    address: "50 Massachusetts Ave NE",
    city: "Washington",
    region: "DC",
    country: "USA",
    floor: "Ground floor",
    latitude: 38.9026,
    longitude: -77.0048,
    status: "verified",
    access_type: "ask_staff",
    purchase_required: false,
    purchase_note: null,
    access_difficulty: "medium",
    access_notes: "Ask the cashier, sometimes the door is jammed",
    access_code_public_allowed: false,
    cost_type: "free",
    cost_amount: null,
    gender_category: "unknown",
    toilet_type: "unknown",
    amenities: {},
    tags: ["sketchy", "cursed"],
    open_hours: { is_24_hours: true },
    cleanliness_score: 1.4,
    safety_score: 1.9,
    privacy_score: 1.7,
    smell_score: 1.2,
    prestige_score: 0.5,
    overall_score: 1.5,
    review_count: 9,
    photo_count: 1,
    verified_at: "2026-01-15T00:00:00.000Z",
    last_verified_at: "2026-01-15T00:00:00.000Z",
    distance_meters: 1490,
  },
  {
    id: "mock-7",
    name: "National Mall Visitor Pavilion",
    venue_name: "Visitor Pavilion",
    description: "Full accessible stall with a fold-down changing table.",
    address: "1000 Jefferson Dr SW",
    city: "Washington",
    region: "DC",
    country: "USA",
    floor: "Ground floor",
    latitude: 38.8913,
    longitude: -77.02,
    status: "verified",
    access_type: "public",
    purchase_required: false,
    purchase_note: null,
    access_difficulty: "easy",
    access_notes: null,
    access_code_public_allowed: false,
    cost_type: "free",
    cost_amount: null,
    gender_category: "accessible",
    toilet_type: "sitting",
    amenities: { wheelchair_accessible: true, baby_changing: true, toilet_paper: true, soap: true, coat_hook: true },
    tags: ["clean", "hidden_gem"],
    open_hours: { is_24_hours: false, open: "08:00", close: "17:30" },
    cleanliness_score: 4.6,
    safety_score: 4.5,
    privacy_score: 4.0,
    smell_score: 4.2,
    prestige_score: 2.4,
    overall_score: 4.5,
    review_count: 14,
    photo_count: 2,
    verified_at: "2026-04-22T00:00:00.000Z",
    last_verified_at: "2026-06-10T00:00:00.000Z",
    distance_meters: 980,
  },
  {
    id: "mock-8",
    name: "Velvet Hour Speakeasy",
    venue_name: "Velvet Hour",
    description: "Unmarked door next to the coat check. Worth the hunt.",
    address: "1100 U St NW",
    city: "Washington",
    region: "DC",
    country: "USA",
    floor: "Basement",
    latitude: 38.9169,
    longitude: -77.0286,
    status: "verified",
    access_type: "code_required",
    purchase_required: true,
    purchase_note: null,
    access_difficulty: "medium",
    access_notes: "Code is printed at the bottom of your receipt",
    access_code_public_allowed: false,
    cost_type: "purchase_required",
    cost_amount: null,
    gender_category: "all_gender",
    toilet_type: "sitting",
    amenities: { mirror: true, full_length_mirror: true, soap: true, hand_dryer: true, outlet: true },
    tags: ["luxury", "elite", "outfit_check", "no_line"],
    open_hours: { is_24_hours: false, open: "18:00", close: "02:00" },
    cleanliness_score: 4.4,
    safety_score: 4.3,
    privacy_score: 4.7,
    smell_score: 4.3,
    prestige_score: 4.6,
    overall_score: 4.5,
    review_count: 10,
    photo_count: 0,
    verified_at: "2026-05-25T00:00:00.000Z",
    last_verified_at: "2026-05-25T00:00:00.000Z",
    distance_meters: 3460,
  },
  {
    id: "mock-9",
    name: "Riverside Wellness Spa",
    venue_name: "Riverside Wellness Spa",
    description: "Day-pass spa on the waterfront. Heated bidet seats.",
    address: "99 Water St SW",
    city: "Washington",
    region: "DC",
    country: "USA",
    floor: "1",
    latitude: 38.8765,
    longitude: -77.0047,
    status: "verified",
    access_type: "customer_only",
    purchase_required: true,
    purchase_note: "Spa membership or day pass required",
    access_difficulty: "medium",
    access_notes: null,
    access_code_public_allowed: false,
    cost_type: "purchase_required",
    cost_amount: null,
    gender_category: "all_gender",
    toilet_type: "bidet",
    amenities: { bidet: true, touchless_flush: true, touchless_sink: true, full_length_mirror: true, soap: true },
    tags: ["luxury", "bidet", "clean", "hidden_gem"],
    open_hours: { is_24_hours: false, open: "09:00", close: "21:00" },
    cleanliness_score: 4.9,
    safety_score: 4.8,
    privacy_score: 4.8,
    smell_score: 4.9,
    prestige_score: 4.4,
    overall_score: 4.8,
    review_count: 7,
    photo_count: 1,
    verified_at: "2026-06-02T00:00:00.000Z",
    last_verified_at: "2026-06-02T00:00:00.000Z",
    distance_meters: 2670,
  },
];
