import type { BathroomNearby } from "../../types/database";

// Mock data for the Map tab + bathroom detail screen while neither is wired
// to Supabase yet (see src/features/bathrooms/api.ts for the real
// get_verified_bathrooms_nearby call this will be swapped for). Shaped
// exactly like BathroomNearby (plus the detail-only extras below) so the
// screens/components don't need to change when the real data lands - only
// the data source does.
//
// Coordinates are real Washington DC neighborhoods, mirroring
// supabase/seed/seed.sql's flavor (not the same rows - this is independent
// throwaway UI mock data, not seeded into any database).

export interface MockReview {
  id: string;
  username: string;
  createdAt: string;
  overall: number;
  caption: string;
  // Score breakdown is optional per review - some reviewers leave a full
  // breakdown, some just leave an overall score + caption. Mirrors
  // Review in src/types/database.ts, minus the bathroom_id/user_id plumbing
  // a real row would have.
  cleanliness?: number;
  safety?: number;
  privacy?: number;
  smell?: number;
  prestige?: number;
}

// Access tips are deliberately separate from reviews (see BathroomDetail
// requirements) and deliberately never contain a real code - see the
// "Important access-code rule" note in enumLabels.ts. Keep new tips to the
// same safe-example style: "ask staff", "code on receipt", "purchase
// required", never an actual code/word.
export interface MockAccessTip {
  id: string;
  username: string;
  createdAt: string;
  note: string;
}

export interface MockBathroomExtras {
  stallCount: number;
  urinalCount: number;
  // Plain labels, not images - there's no real photo upload yet (see
  // src/components/bathroom/PhotoCarousel.tsx), so the carousel renders
  // these as placeholder tiles instead of pretending to have real photos.
  photoPlaceholders: string[];
  reviews: MockReview[];
  accessTips: MockAccessTip[];
}

export type MockBathroom = BathroomNearby & MockBathroomExtras;

export const MOCK_BATHROOMS: MockBathroom[] = [
  {
    id: "mock-1",
    name: "Eastern Market Plaza Restroom",
    venue_name: "Eastern Market Plaza",
    description: "City-maintained public restroom right outside the market hall.",
    address: "225 7th St SE",
    city: "Washington",
    region: "DC",
    country: "USA",
    floor: "Ground floor",
    latitude: 38.8847,
    longitude: -76.9956,
    status: "verified",
    access_type: "public",
    purchase_required: false,
    purchase_note: null,
    access_difficulty: "easy",
    access_notes: null,
    access_code_public_allowed: false,
    cost_type: "free",
    cost_amount: null,
    gender_category: "all_gender",
    toilet_type: "sitting",
    amenities: { toilet_paper: true, soap: true, hand_dryer: true, wheelchair_accessible: true },
    tags: ["clean", "emergency_save"],
    open_hours: { is_24_hours: false, open: "07:00", close: "20:00" },
    cleanliness_score: 4.3,
    safety_score: 4.1,
    privacy_score: 3.8,
    smell_score: 4.0,
    prestige_score: 2.1,
    overall_score: 4.2,
    review_count: 12,
    photo_count: 3,
    verified_at: "2026-04-01T00:00:00.000Z",
    last_verified_at: "2026-06-15T00:00:00.000Z",
    distance_meters: 320,
    stallCount: 3,
    urinalCount: 1,
    photoPlaceholders: ["Entrance", "Sink area", "Stall row", "Hand dryer"],
    reviews: [
      {
        id: "mock-1-review-1",
        username: "@dc_dweller",
        createdAt: "2026-06-18T14:30:00.000Z",
        overall: 4.5,
        caption: "Surprisingly clean for a public restroom right by the market. Smells like soap, not standing water.",
        cleanliness: 4.5,
        safety: 4,
        privacy: 4,
        smell: 4.5,
        prestige: 2,
      },
      {
        id: "mock-1-review-2",
        username: "@market_regular",
        createdAt: "2026-06-10T09:15:00.000Z",
        overall: 4,
        caption: "Lines get long on Saturdays but it's kept up well.",
      },
    ],
    accessTips: [
      {
        id: "mock-1-tip-1",
        username: "@dc_dweller",
        createdAt: "2026-06-18T14:32:00.000Z",
        note: "Open to anyone, no purchase needed - just walk in from the plaza side.",
      },
    ],
  },
  {
    id: "mock-2",
    name: "Capitol Grounds Coffee",
    venue_name: "Capitol Grounds Coffee",
    description: "Single-occupancy restroom behind the espresso bar.",
    address: "301 Pennsylvania Ave SE",
    city: "Washington",
    region: "DC",
    country: "USA",
    floor: "1",
    latitude: 38.8857,
    longitude: -76.9942,
    status: "verified",
    access_type: "purchase_required",
    purchase_required: true,
    purchase_note: "Must buy any menu item",
    access_difficulty: "easy",
    access_notes: "Ask the barista for the key after you order",
    access_code_public_allowed: false,
    cost_type: "purchase_required",
    cost_amount: null,
    gender_category: "all_gender",
    toilet_type: "sitting",
    amenities: { toilet_paper: true, soap: true, hand_dryer: true, mirror: true },
    tags: ["clean", "restaurant"],
    open_hours: { is_24_hours: false, open: "06:30", close: "19:00" },
    cleanliness_score: 4.0,
    safety_score: 4.4,
    privacy_score: 3.9,
    smell_score: 3.8,
    prestige_score: 2.6,
    overall_score: 4.0,
    review_count: 8,
    photo_count: 1,
    verified_at: "2026-04-10T00:00:00.000Z",
    last_verified_at: "2026-06-01T00:00:00.000Z",
    distance_meters: 540,
    stallCount: 1,
    urinalCount: 0,
    photoPlaceholders: ["Door", "Sink", "Mirror"],
    reviews: [
      {
        id: "mock-2-review-1",
        username: "@latte_logs",
        createdAt: "2026-06-12T08:00:00.000Z",
        overall: 4,
        caption: "Single stall, always clean, smells like the coffee shop.",
        cleanliness: 4,
        safety: 4.5,
        privacy: 4,
        smell: 4,
      },
      {
        id: "mock-2-review-2",
        username: "@espresso_em",
        createdAt: "2026-05-30T11:20:00.000Z",
        overall: 4,
        caption: "Worth the price of a drip coffee.",
      },
    ],
    accessTips: [
      {
        id: "mock-2-tip-1",
        username: "@latte_logs",
        createdAt: "2026-06-12T08:02:00.000Z",
        note: "Buy literally anything, then ask the barista for the key.",
      },
    ],
  },
  {
    id: "mock-3",
    name: "The Meridian Hotel Lobby",
    venue_name: "The Meridian Hotel",
    description: "Marble-and-brass restroom tucked past the lobby bar.",
    address: "1500 New Hampshire Ave NW",
    city: "Washington",
    region: "DC",
    country: "USA",
    floor: "Lobby",
    latitude: 38.9097,
    longitude: -77.0434,
    status: "verified",
    access_type: "ask_staff",
    purchase_required: false,
    purchase_note: null,
    access_difficulty: "easy",
    access_notes: "Walk in like you belong, restrooms are past the lobby bar",
    access_code_public_allowed: false,
    cost_type: "free",
    cost_amount: null,
    gender_category: "all_gender",
    toilet_type: "sitting",
    amenities: { mirror: true, full_length_mirror: true, soap: true, hand_dryer: true, outlet: true },
    tags: ["hotel", "luxury", "elite", "outfit_check"],
    open_hours: { is_24_hours: true },
    cleanliness_score: 4.8,
    safety_score: 4.7,
    privacy_score: 4.5,
    smell_score: 4.6,
    prestige_score: 4.9,
    overall_score: 4.8,
    review_count: 21,
    photo_count: 5,
    verified_at: "2026-03-20T00:00:00.000Z",
    last_verified_at: "2026-06-20T00:00:00.000Z",
    distance_meters: 1850,
    stallCount: 4,
    urinalCount: 2,
    photoPlaceholders: ["Lobby hallway", "Marble sink", "Stall", "Full mirror", "Soap dispenser"],
    reviews: [
      {
        id: "mock-3-review-1",
        username: "@hotel_hopper",
        createdAt: "2026-06-21T19:45:00.000Z",
        overall: 5,
        caption: "Felt like I was getting ready for a gala. Full-length mirror, great lighting.",
        cleanliness: 5,
        safety: 5,
        privacy: 4.5,
        smell: 5,
        prestige: 5,
      },
      {
        id: "mock-3-review-2",
        username: "@outfit_check_dc",
        createdAt: "2026-06-05T21:10:00.000Z",
        overall: 4.5,
        caption: "Best lighting in the city for a mirror check.",
      },
    ],
    accessTips: [
      {
        id: "mock-3-tip-1",
        username: "@hotel_hopper",
        createdAt: "2026-06-21T19:47:00.000Z",
        note: "Walk in confidently, restrooms are past the lobby bar - nobody stops you.",
      },
    ],
  },
  {
    id: "mock-4",
    name: "Foggy Bottom University Student Center",
    venue_name: "University Student Center",
    description: "3rd floor restroom, usually empty between classes.",
    address: "800 21st St NW",
    city: "Washington",
    region: "DC",
    country: "USA",
    floor: "3",
    latitude: 38.9,
    longitude: -77.0481,
    status: "verified",
    access_type: "public",
    purchase_required: false,
    purchase_note: null,
    access_difficulty: "easy",
    access_notes: null,
    access_code_public_allowed: false,
    cost_type: "free",
    cost_amount: null,
    gender_category: "all_gender",
    toilet_type: "mixed",
    amenities: { toilet_paper: true, soap: true, hand_dryer: true, wheelchair_accessible: true },
    tags: ["campus", "emergency_save", "no_line"],
    open_hours: { is_24_hours: false, open: "07:00", close: "23:00" },
    cleanliness_score: 3.4,
    safety_score: 3.9,
    privacy_score: 3.5,
    smell_score: 3.3,
    prestige_score: 1.8,
    overall_score: 3.5,
    review_count: 16,
    photo_count: 0,
    verified_at: "2026-02-28T00:00:00.000Z",
    last_verified_at: "2026-05-30T00:00:00.000Z",
    distance_meters: 2210,
    stallCount: 5,
    urinalCount: 3,
    photoPlaceholders: ["Hallway entrance", "Sink row", "Stall"],
    reviews: [
      {
        id: "mock-4-review-1",
        username: "@campus_commuter",
        createdAt: "2026-06-08T13:00:00.000Z",
        overall: 3.5,
        caption: "Decent between classes, gets busy at the top of the hour.",
        cleanliness: 3.5,
        safety: 4,
        privacy: 3.5,
        smell: 3,
      },
    ],
    accessTips: [
      {
        id: "mock-4-tip-1",
        username: "@campus_commuter",
        createdAt: "2026-06-08T13:02:00.000Z",
        note: "Open to the public, no student ID needed.",
      },
    ],
  },
  {
    id: "mock-5",
    name: "The Hayworth Society Club",
    venue_name: "The Hayworth Society Club",
    description: "Members-only social club. The restroom alone is worth it.",
    address: "1523 Wisconsin Ave NW",
    city: "Washington",
    region: "DC",
    country: "USA",
    floor: "2",
    latitude: 38.9076,
    longitude: -77.0723,
    status: "verified",
    access_type: "private_rare",
    purchase_required: false,
    purchase_note: null,
    access_difficulty: "invite_only",
    access_notes: "Members-only; a member has to sign you in",
    access_code_public_allowed: false,
    cost_type: "free",
    cost_amount: null,
    gender_category: "all_gender",
    toilet_type: "bidet",
    amenities: { bidet: true, full_length_mirror: true, mirror: true, soap: true, outlet: true, touchless_flush: true },
    tags: ["luxury", "private_rare", "elite", "hidden_gem", "bidet"],
    open_hours: { is_24_hours: false, open: "11:00", close: "01:00" },
    cleanliness_score: 4.9,
    safety_score: 4.8,
    privacy_score: 4.9,
    smell_score: 4.7,
    prestige_score: 5.0,
    overall_score: 4.9,
    review_count: 6,
    photo_count: 2,
    verified_at: "2026-05-01T00:00:00.000Z",
    last_verified_at: "2026-06-18T00:00:00.000Z",
    distance_meters: 4120,
    stallCount: 2,
    urinalCount: 1,
    photoPlaceholders: ["Entry hall", "Bidet seat", "Full mirror", "Velvet bench"],
    reviews: [
      {
        id: "mock-5-review-1",
        username: "@member_since_22",
        createdAt: "2026-06-19T22:00:00.000Z",
        overall: 5,
        caption: "Heated bidet seat in a members' club. This is the bathroom flex of the year.",
        cleanliness: 5,
        safety: 5,
        privacy: 5,
        smell: 4.5,
        prestige: 5,
      },
    ],
    accessTips: [
      {
        id: "mock-5-tip-1",
        username: "@member_since_22",
        createdAt: "2026-06-19T22:02:00.000Z",
        note: "Members only - a current member has to sign you in at the door.",
      },
    ],
  },
  {
    id: "mock-6",
    name: "Tunnel Station Mart Restroom",
    venue_name: "Tunnel Station Mart",
    description: "Behind the snack aisle. Bring your own paper towels.",
    address: "50 Massachusetts Ave NE",
    city: "Washington",
    region: "DC",
    country: "USA",
    floor: "Ground floor",
    latitude: 38.9026,
    longitude: -77.0048,
    status: "verified",
    access_type: "ask_staff",
    purchase_required: false,
    purchase_note: null,
    access_difficulty: "medium",
    access_notes: "Ask the cashier, sometimes the door is jammed",
    access_code_public_allowed: false,
    cost_type: "free",
    cost_amount: null,
    gender_category: "unknown",
    toilet_type: "unknown",
    amenities: {},
    tags: ["sketchy", "cursed"],
    open_hours: { is_24_hours: true },
    cleanliness_score: 1.4,
    safety_score: 1.9,
    privacy_score: 1.7,
    smell_score: 1.2,
    prestige_score: 0.5,
    overall_score: 1.5,
    review_count: 9,
    photo_count: 1,
    verified_at: "2026-01-15T00:00:00.000Z",
    last_verified_at: "2026-01-15T00:00:00.000Z",
    distance_meters: 1490,
    stallCount: 1,
    urinalCount: 1,
    photoPlaceholders: ["Door", "Sink"],
    reviews: [
      {
        id: "mock-6-review-1",
        username: "@late_night_dc",
        createdAt: "2026-06-02T01:30:00.000Z",
        overall: 1.5,
        caption: "Lock is broken and it smells like the snack aisle's worst day.",
        cleanliness: 1,
        safety: 2,
        privacy: 1.5,
        smell: 1,
      },
      {
        id: "mock-6-review-2",
        username: "@brave_traveler",
        createdAt: "2026-05-20T23:50:00.000Z",
        overall: 1.5,
        caption: "Only use if it's a real emergency.",
      },
    ],
    accessTips: [
      {
        id: "mock-6-tip-1",
        username: "@late_night_dc",
        createdAt: "2026-06-02T01:32:00.000Z",
        note: "Ask the cashier - door sticks, push hard.",
      },
    ],
  },
  {
    id: "mock-7",
    name: "National Mall Visitor Pavilion",
    venue_name: "Visitor Pavilion",
    description: "Full accessible stall with a fold-down changing table.",
    address: "1000 Jefferson Dr SW",
    city: "Washington",
    region: "DC",
    country: "USA",
    floor: "Ground floor",
    latitude: 38.8913,
    longitude: -77.02,
    status: "verified",
    access_type: "public",
    purchase_required: false,
    purchase_note: null,
    access_difficulty: "easy",
    access_notes: null,
    access_code_public_allowed: false,
    cost_type: "free",
    cost_amount: null,
    gender_category: "accessible",
    toilet_type: "sitting",
    amenities: { wheelchair_accessible: true, baby_changing: true, toilet_paper: true, soap: true, coat_hook: true },
    tags: ["clean", "hidden_gem"],
    open_hours: { is_24_hours: false, open: "08:00", close: "17:30" },
    cleanliness_score: 4.6,
    safety_score: 4.5,
    privacy_score: 4.0,
    smell_score: 4.2,
    prestige_score: 2.4,
    overall_score: 4.5,
    review_count: 14,
    photo_count: 2,
    verified_at: "2026-04-22T00:00:00.000Z",
    last_verified_at: "2026-06-10T00:00:00.000Z",
    distance_meters: 980,
    stallCount: 6,
    urinalCount: 2,
    photoPlaceholders: ["Entrance ramp", "Accessible stall", "Changing table", "Sink row"],
    reviews: [
      {
        id: "mock-7-review-1",
        username: "@stroller_dc",
        createdAt: "2026-06-14T15:20:00.000Z",
        overall: 4.5,
        caption: "Real changing table and a stall big enough for a wheelchair. Rare downtown.",
        cleanliness: 4.5,
        safety: 4.5,
        privacy: 4,
        smell: 4.5,
      },
    ],
    accessTips: [
      {
        id: "mock-7-tip-1",
        username: "@stroller_dc",
        createdAt: "2026-06-14T15:22:00.000Z",
        note: "Free and open to everyone, no ticket needed for the restroom itself.",
      },
    ],
  },
  {
    id: "mock-8",
    name: "Velvet Hour Speakeasy",
    venue_name: "Velvet Hour",
    description: "Unmarked door next to the coat check. Worth the hunt.",
    address: "1100 U St NW",
    city: "Washington",
    region: "DC",
    country: "USA",
    floor: "Basement",
    latitude: 38.9169,
    longitude: -77.0286,
    status: "verified",
    access_type: "code_required",
    purchase_required: true,
    purchase_note: null,
    access_difficulty: "medium",
    access_notes: "Code is printed at the bottom of your receipt",
    access_code_public_allowed: false,
    cost_type: "purchase_required",
    cost_amount: null,
    gender_category: "all_gender",
    toilet_type: "sitting",
    amenities: { mirror: true, full_length_mirror: true, soap: true, hand_dryer: true, outlet: true },
    tags: ["luxury", "elite", "outfit_check", "no_line"],
    open_hours: { is_24_hours: false, open: "18:00", close: "02:00" },
    cleanliness_score: 4.4,
    safety_score: 4.3,
    privacy_score: 4.7,
    smell_score: 4.3,
    prestige_score: 4.6,
    overall_score: 4.5,
    review_count: 10,
    photo_count: 0,
    verified_at: "2026-05-25T00:00:00.000Z",
    last_verified_at: "2026-05-25T00:00:00.000Z",
    distance_meters: 3460,
    stallCount: 2,
    urinalCount: 1,
    photoPlaceholders: ["Unmarked door", "Sink", "Mirror", "Dim hallway"],
    reviews: [
      {
        id: "mock-8-review-1",
        username: "@speakeasy_scout",
        createdAt: "2026-06-16T23:15:00.000Z",
        overall: 4.5,
        caption: "Dim, moody lighting and it actually smells good. Matches the vibe of the bar.",
        cleanliness: 4.5,
        safety: 4,
        privacy: 5,
        smell: 4,
      },
    ],
    accessTips: [
      {
        id: "mock-8-tip-1",
        username: "@speakeasy_scout",
        createdAt: "2026-06-16T23:17:00.000Z",
        note: "Code's printed at the bottom of your receipt - easy to miss the first time.",
      },
    ],
  },
  {
    id: "mock-9",
    name: "Riverside Wellness Spa",
    venue_name: "Riverside Wellness Spa",
    description: "Day-pass spa on the waterfront. Heated bidet seats.",
    address: "99 Water St SW",
    city: "Washington",
    region: "DC",
    country: "USA",
    floor: "1",
    latitude: 38.8765,
    longitude: -77.0047,
    status: "verified",
    access_type: "customer_only",
    purchase_required: true,
    purchase_note: "Spa membership or day pass required",
    access_difficulty: "medium",
    access_notes: null,
    access_code_public_allowed: false,
    cost_type: "purchase_required",
    cost_amount: null,
    gender_category: "all_gender",
    toilet_type: "bidet",
    amenities: { bidet: true, touchless_flush: true, touchless_sink: true, full_length_mirror: true, soap: true },
    tags: ["luxury", "bidet", "clean", "hidden_gem"],
    open_hours: { is_24_hours: false, open: "09:00", close: "21:00" },
    cleanliness_score: 4.9,
    safety_score: 4.8,
    privacy_score: 4.8,
    smell_score: 4.9,
    prestige_score: 4.4,
    overall_score: 4.8,
    review_count: 7,
    photo_count: 1,
    verified_at: "2026-06-02T00:00:00.000Z",
    last_verified_at: "2026-06-02T00:00:00.000Z",
    distance_meters: 2670,
    stallCount: 3,
    urinalCount: 0,
    photoPlaceholders: ["Spa entrance", "Bidet seat", "Touchless sink", "Towel station"],
    reviews: [
      {
        id: "mock-9-review-1",
        username: "@spa_day_dc",
        createdAt: "2026-06-09T17:40:00.000Z",
        overall: 5,
        caption: "Heated bidet, touchless everything. Worth the day pass alone.",
        cleanliness: 5,
        safety: 5,
        privacy: 5,
        smell: 5,
        prestige: 4.5,
      },
    ],
    accessTips: [
      {
        id: "mock-9-tip-1",
        username: "@spa_day_dc",
        createdAt: "2026-06-09T17:42:00.000Z",
        note: "Buy a day pass or show a membership at the front desk.",
      },
    ],
  },
];
