/// <reference types="expo/types" />

// NOTE: this file is normally auto-generated by Expo CLI on first run.
// It's checked in here so `tsc --noEmit` works before anyone has run
// `expo start` for the first time.
